services:
  runpod:
    image: Squister777/squishy-runpod:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=all
      - MAX_CONCURRENCY=300
      - GPU_MEMORY_UTILIZATION=0.95
      - TRUST_REMOTE_CODE=1
      - DEFAULT_BATCH_SIZE=50
      - DEFAULT_MIN_BATCH_SIZE=1
      - DEFAULT_BATCH_SIZE_GROWTH_FACTOR=3
      - DISABLE_LOG_STATS=0
      - DISABLE_LOG_REQUESTS=0
      - RAW_OPENAI_OUTPUT=1
      - TOKENIZER_MODE=auto
      - BLOCK_SIZE=16
      - SWAP_SPACE=4
      - ENFORCE_EAGER=0
      - MAX_SEQ_LEN_TO_CAPTURE=8192
      - DISABLE_CUSTOM_ALL_REDUCE=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]